apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-cosmos
  labels:
    deploymentInformation: nim-cosmos
spec:
  selector:
    matchLabels:
      deploymentInformation: nim-cosmos
  template:
    metadata:
      labels:
        deploymentInformation: nim-cosmos
    spec:
      hostname: nim-cosmos-pod  # Custom hostname for the pod
      dnsPolicy: None
      dnsConfig:
        nameservers:
         - 8.8.8.8
         - 1.1.1.1
      hostNetwork: true  # Use the host's network
      containers:
      - name: cosmos-nim
        image: nvcr.io/nim/nvidia/cosmos-predict1-7b-text2world:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: nim-cache
          mountPath: /opt/nim/.cache
        resources:
          limits:
            nvidia.com/gpu: "1"        # e.g. "1"
            cpu: "2"                    # e.g. "2"
            memory: "3000M"              # e.g. "4000M"
            ephemeral-storage: "10G"  # Use ephemeral-storage instead of storage, e.g. "10G"
          requests:
            nvidia.com/gpu: "1"       # e.g. "1"
            cpu: "2"                  # e.g. "1"
            memory: "3000M"            # e.g. "2000M"
            ephemeral-storage: "10G"  # Use ephemeral-storage instead of storage, e.g. "5G"
      volumes:
      - name: nim-cache
        emptyDir: {}
      imagePullSecrets:
      - name: secret-nvidia
      restartPolicy: Always
