apiVersion: v1
kind: Service
metadata:
  deploymentInformation: nim-cosmos-service
spec:
  selector:
    deploymentInformation: nim-cosmos
  ports:
    - name: tcp
      port: 80  # Port exposed by the service
      protocol: TCP
      targetPort: 8000  # Port on the pod
  type: ClusterIP
